# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N8ZWOJq7DZnRXwZXotH_KNat_QH0Y8x8
"""

# Selection Sort

arr = list(map(int, input("Enter elements: ").split()))
n = len(arr)

comparisons = 0
swaps = 0

for i in range(n):
    min_index = i

    for j in range(i + 1, n):
        comparisons += 1
        if arr[j] < arr[min_index]:
            min_index = j

    if min_index != i:
        arr[i], arr[min_index] = arr[min_index], arr[i]
        swaps += 1

print("\nSorted Array:", arr)

print("\nComparisons:", comparisons)
print("Swaps:", swaps)

print("\nTime Complexity")
print("Best Case    : O(n^2)")
print("Average Case : O(n^2)")
print("Worst Case   : O(n^2)")

print("\nSpace Complexity")
print("O(1)")